/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.testarquillianextension.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.LocalizedModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Entity service. Represents a row in the &quot;Entity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.testarquillianextension.model.impl.EntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.testarquillianextension.model.impl.EntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entity
 * @see com.liferay.testarquillianextension.model.impl.EntityImpl
 * @see com.liferay.testarquillianextension.model.impl.EntityModelImpl
 * @generated
 */
@ProviderType
public interface EntityModel extends BaseModel<Entity>, LocalizedModel,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a entity model instance should use the {@link Entity} interface instead.
	 */

	/**
	 * Returns the primary key of this entity.
	 *
	 * @return the primary key of this entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this entity.
	 *
	 * @param primaryKey the primary key of this entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this entity.
	 *
	 * @return the uuid of this entity
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this entity.
	 *
	 * @param uuid the uuid of this entity
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the entity ID of this entity.
	 *
	 * @return the entity ID of this entity
	 */
	public long getEntityId();

	/**
	 * Sets the entity ID of this entity.
	 *
	 * @param entityId the entity ID of this entity
	 */
	public void setEntityId(long entityId);

	/**
	 * Returns the group ID of this entity.
	 *
	 * @return the group ID of this entity
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this entity.
	 *
	 * @param groupId the group ID of this entity
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this entity.
	 *
	 * @return the company ID of this entity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this entity.
	 *
	 * @param companyId the company ID of this entity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this entity.
	 *
	 * @return the user ID of this entity
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this entity.
	 *
	 * @param userId the user ID of this entity
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this entity.
	 *
	 * @return the user uuid of this entity
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this entity.
	 *
	 * @param userUuid the user uuid of this entity
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this entity.
	 *
	 * @return the user name of this entity
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this entity.
	 *
	 * @param userName the user name of this entity
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this entity.
	 *
	 * @return the create date of this entity
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this entity.
	 *
	 * @param createDate the create date of this entity
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this entity.
	 *
	 * @return the modified date of this entity
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this entity.
	 *
	 * @param modifiedDate the modified date of this entity
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the total of this entity.
	 *
	 * @return the total of this entity
	 */
	public long getTotal();

	/**
	 * Sets the total of this entity.
	 *
	 * @param total the total of this entity
	 */
	public void setTotal(long total);

	/**
	 * Returns the name of this entity.
	 *
	 * @return the name of this entity
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this entity.
	 *
	 * @param name the name of this entity
	 */
	public void setName(String name);

	/**
	 * Returns the description of this entity.
	 *
	 * @return the description of this entity
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this entity in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this entity
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this entity in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this entity. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this entity in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this entity
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this entity in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this entity
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this entity.
	 *
	 * @return the locales and localized descriptions of this entity
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this entity.
	 *
	 * @param description the description of this entity
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this entity in the language.
	 *
	 * @param description the localized description of this entity
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this entity in the language, and sets the default locale.
	 *
	 * @param description the localized description of this entity
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this entity from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this entity
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this entity from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this entity
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.testarquillianextension.model.Entity entity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.testarquillianextension.model.Entity> toCacheModel();

	@Override
	public com.liferay.testarquillianextension.model.Entity toEscapedModel();

	@Override
	public com.liferay.testarquillianextension.model.Entity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}